# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directories:
      - /
      - /interceptors/logging/examples
      - /providers/prometheus
      - /examples
    schedule:
      interval: weekly
